// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Codartis.SoftVis.VisualStudioIntegration
{
    static class Vsix
    {
        public const string Id = "7481ead5-87e4-4ac0-86d1-317e7adab60c";
        public const string Name = "Quick Diagram Tool for C#";
        public const string Description = @"Code visualization tool for C# to quickly explore, navigate and document source code structure and relationships. Similar to the Code Map feature of Visual Studio Enterprise Edition but much more lightweight.
This is an experimental release that supports type inheritance and interface implementation relationships only. Later versions will show a lot more (namespaces, type members, method calls, property read/write, object creation, etc.)";
        public const string Language = "en-US";
        public const string Version = "0.5.0.0";
        public const string Author = "Codartis";
        public const string Tags = "code;visualize;quick;diagram;c#;csharp;tool;inheritance;interface;implementation;codemap;map";
    }
}
