// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Codartis.SoftVis.VisualStudioIntegration
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string SoftVisPackageGuidString = "198d9322-583a-4112-a2a8-61f4c0818966";
        public const string DiagramToolWindowGuidString = "02d1f8b9-d0a0-4ccb-9687-e6f0f781ad9e";
        public const string SoftVisCommandSetGuidString = "d45a1864-ab94-44fd-81ca-2602753b60d3";
        public const string AutoSizeImageGuidString = "581dc3ea-bdc2-424c-9c85-e4227c6ca1ad";
        public const string CopyImageGuidString = "59e1b98a-0b42-4c39-a23f-e3b7b02e5f10";
        public const string DeleteImageGuidString = "d3a2883a-16c1-44ed-82d6-7eb18c4b0b15";
        public const string DiagramImageGuidString = "0d784288-3295-4acd-b754-1cae3713a02e";
        public const string RefreshImageGuidString = "f88b78f7-ac5d-421d-8eb4-ba2b72a99a4b";
        public const string SaveImageGuidString = "6cd2d9b8-33f6-40b7-800e-f4228cd0418a";
        public const string AddToDiagramImageGuidString = "77eafd6d-6780-473e-bba7-592b13e61b79";
        public const string AddToDiagramWithHierarchyImageGuidString = "cb459c8b-1aa2-4882-b92b-10f6f5f8a074";
        public const string ExpandAllImageGuidString = "482d62f8-9816-4a2d-9e2a-183be2e2896f";
        public const string CollapseAllImageGuidString = "748226c2-748d-4db1-b692-18cfb4654b47";
        public const string SourceCodeTextEditorGuidString = "8b382828-6202-11d1-8870-0000f87579d2";
        public static Guid SoftVisPackageGuid = new Guid(SoftVisPackageGuidString);
        public static Guid DiagramToolWindowGuid = new Guid(DiagramToolWindowGuidString);
        public static Guid SoftVisCommandSetGuid = new Guid(SoftVisCommandSetGuidString);
        public static Guid AutoSizeImageGuid = new Guid(AutoSizeImageGuidString);
        public static Guid CopyImageGuid = new Guid(CopyImageGuidString);
        public static Guid DeleteImageGuid = new Guid(DeleteImageGuidString);
        public static Guid DiagramImageGuid = new Guid(DiagramImageGuidString);
        public static Guid RefreshImageGuid = new Guid(RefreshImageGuidString);
        public static Guid SaveImageGuid = new Guid(SaveImageGuidString);
        public static Guid AddToDiagramImageGuid = new Guid(AddToDiagramImageGuidString);
        public static Guid AddToDiagramWithHierarchyImageGuid = new Guid(AddToDiagramWithHierarchyImageGuidString);
        public static Guid ExpandAllImageGuid = new Guid(ExpandAllImageGuidString);
        public static Guid CollapseAllImageGuid = new Guid(CollapseAllImageGuidString);
        public static Guid SourceCodeTextEditorGuid = new Guid(SourceCodeTextEditorGuidString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolWindowToolbar = 0x0001;
        public const int DiagramMainMenu = 0x0002;
        public const int ExportImageMenuController = 0x0003;
        public const int MainMenuCommandGroup = 0x0032;
        public const int CodeEditorCommandGroup = 0x0033;
        public const int ExportImageCommandGroup = 0x0034;
        public const int ToolbarGroup1 = 0x0035;
        public const int ToolbarGroup2 = 0x0036;
        public const int ToolbarImageGroup = 0x0037;
        public const int ToolbarGroup3 = 0x0038;
        public const int ShowDiagramWindowCommand = 0x0064;
        public const int AddToDiagramCommand = 0x0065;
        public const int AddToDiagramWithHierarchyCommand = 0x0066;
        public const int ClearModelCommand = 0x0067;
        public const int ClearDiagramCommand = 0x0068;
        public const int UpdateModelFromSourceCommand = 0x0069;
        public const int CopyToClipboardCommand = 0x006A;
        public const int ExportToFileCommand = 0x006B;
        public const int ImageDpiComboCommand = 0x006C;
        public const int ImageDpiComboGetItemsCommand = 0x006D;
        public const int ZoomToDiagramCommand = 0x006E;
        public const int ExpandAllNodesCommand = 0x006F;
        public const int CollapseAllNodesCommand = 0x0070;
        public const int AutoSizeImageId = 0x0001;
        public const int CopyImageId = 0x0001;
        public const int DeleteImageId = 0x0001;
        public const int DiagramImageId = 0x0001;
        public const int RefreshImageId = 0x0001;
        public const int SaveImageId = 0x0001;
        public const int AddToDiagramImageId = 0x0001;
        public const int AddToDiagramWithHierarchyImageId = 0x0001;
        public const int ExpandAllImageId = 0x0001;
        public const int CollapseAllImageId = 0x0001;
    }
}
